# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: cppfmt
        name: c[[]] Code Formatter
        language: system
        entry: clang-format -i
        types: [c++]
        files: \.cpp$|\.hpp$|\.c$|\.h$
        verbose: true
